### ISSUE TITLE
Return a local table instead of creating a global one when requiring the module

### ISSUE THREAD

**Issue by kikito** [felipedaragon/selenite#1]
So instead of:

    require 'selenite'
    slx.foo.bar(whatever)

You do this instead:

    local slx = require 'selenite'
    slx.foo.bar(whatever)

**Comment by felipedaragon** [comment]
There is a limitation involving the pLua's LuaObject component registration that prevents me from implementing this today.

**Comment by felipedaragon** [comment]
It should work now! :)
